* firmforth

firmforth is a just-in-time-compiling forth-like system using [[http://libfirm.org][libfirm]].
It is small and comprehensible and was written to evaluate
JIT-compilation using libfirm.

** Design

Firmforth is built around a dictionary of functions that can be
invoked for an effect on a stack of values or a side effect.  It also
sports a typical forth outer interpreter.  In interpreter mode, it
executes the words that are input.  In compilation mode, its action
depends on whether an entered word is flagged immediate.  Immediate
words - e.g. "if" - are still executed right-away and implement the
compiler itself.  Normal words end up as Call nodes in the
intermediate language.

When the definition of a new word is complete, libfirm-provided
optimizations are invoked, possibly inlining Calls of functions for
which the intermediate representation is available.  An assembly file
is then generated by libfirm and assembled into a shared object.  This
is in turn loaded into the program using dlopen() and the word is
added to the dictionary.  The IR is also kept around for future
inlining of the word.

** Usage

A couple of standard forth words are written in forth itself in the
file =core.fifo=.  To get an interactive session with these words
defined, you could invoke firmforth like this:

: make && cat core.fifo - | ./firmforth

Some of the forth words are currently implemented in C.  In order to
be able to inline them into new words for a major speedup, the
intermediate representation for them can be made available by invoking
[[https://github.com/MatzeB/cparser][cparser]] like this:

: cparser --export-ir firmforth.c

** Goals
- [X] Interactively compile forth words using graphs of Call nodes
- [X] Add control flow primitives
- [X] Keep IR of newly defined words around and inline them
- [X] Keep IR of statically defined words around and inline them

** Benchmark
The table below lists times required for compiling and executing the
word =fibonacci= as defined in =core.fifo= for the number 35 on my
machine for various forth systems.

|                                | compile [s] | execute [s] |
|--------------------------------+-------------+-------------|
| firmforth 8543639              |        0.60 |        0.26 |
| GNU Gforth 0.7.2 (gforth-fast) |        0.00 |        0.39 |
| stubforth 5745163              |        0.00 |        0.83 |

** Authors

Andreas Seltenreich <seltenreich@gmx.de>
